### PR TITLE
feat: toEsObservable and SymbolShim

### PR DESCRIPTION
**Pull request by gdi2290**

### CODE REVIEW

**Comment by michaelbpaulson** [comment]
Since this is both for falcor and falcor-http-datasource, do you think you could just create an npm package for this?  If we don't do it that way then we will have this code duplicated 2x within falcor.

**Comment by gdi2290** [comment]
I think @blesh was thinking about make the module. This is something we need for Angular 2 (because it uses Rx 5) and Falcor to play well with each other's Observables

**Comment by blesh** [comment]
> I think @blesh was thinking about making the module. 

Totally, just @blesh hasn't had time. :\

**Comment by michaelbpaulson** [comment]
@blesh are you committing to this?

**Comment by gdi2290** [comment]
I can also make the module ;) or at least create the basic version until Ben has time

**Comment by blesh** [comment]
@michaelbpaulson yes. But I'm unsure on the timeline.

**Comment by michaelbpaulson** [comment]
Going to close this down since RxJS will build the shim library.  Once done, we can just include the relevant bits via npm.

**Comment by gdi2290** [comment]
Sounds good

**Pull request closed without merging**
